### ISSUE TITLE
Implement Analyze Command for Prometheus

### ISSUE THREAD

**Issue by nicolastakashi** [prometheus-operator/poctl#25]
During the deployment of a Prometheus object, there are various configurations that can cause issues, leading to Prometheus not functioning properly.

For example:

- The lack of proper Cluster Roles and Role Bindings to allow Prometheus to discover targets.
- Misconfiguration of selectors for Prometheus to select monitoring objects such as ServiceMonitor and PodMonitor.

With this in mind, it would be beneficial to have an analyze command for the Prometheus type to identify potential problems and assist in troubleshooting.

**Comment by heliapb** [comment]
Hi @nicolastakashi I would like to work on this issue
