### ISSUE TITLE
Implement Analyze Command for AlertManager

### ISSUE THREAD

**Issue by nicolastakashi** [prometheus-operator/poctl#35]
During the deployment of a AlertManager object, there are various configurations that can cause issues, leading to AlertManager not functioning properly.

For example:

- The lack of proper Cluster Roles and Role Bindings to allow AlertManager to work as expected.
- Misconfiguration of selectors for AlertManager to select AlertManagerConfig.

With this in mind, it would be beneficial to have an analyze command for the AlertManager type to identify potential problems and assist in troubleshooting.

**Comment by heliapb** [comment]
Hi @nicolastakashi I would like to work on this issue
